# Generated by Django 2.2.12 on 2020-09-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='descrpiton',
            field=models.CharField(max_length=255, null=True, verbose_name='وصف الملف المرفق'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='check_responsabl_group_opnion',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='تحقق مسؤول التواصل أو المتعاونين تسجيل المعلومات الواردة حول طالب الدعم'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='confirm_stat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الحالة'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='cruntly_adre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تقيم خطورة مكان الإقامة الحالي'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='date_of_updat',
            field=models.DateField(auto_now=True, null=True, verbose_name='تاريخ اخر تحديث'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='date_of_verficaton',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء من التحقق'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='hase_violants',
            field=models.CharField(blank=True, default=1, max_length=30, null=True, verbose_name='تعرّض مُقدّم الطلب لأيّ انتهاكات'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='is_thier_heate_speech',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='-\tهل يُحرّض على العنف والكراهية؟ أو الإرهاب أو الطائفيّة؟'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='is_thier_info_correct',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل قدم معلومات صحيحة ضمن طلب الدعم'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='mark_rspect_coppyright',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name=' تقيم شرح لاحترام حقوق النشر'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='mark_rspect_right_human',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='تقيم احترام حقوق الانسان'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='medical_state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='-الوضع الطبي'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='note_rspect_coppyright',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح لاحترام حقوق النشر'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='note_rspect_legal_coppyright',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح لمراعاة خصوصية الصور'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='note_rspect_right_human',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح لتقيم احترام حقوق الانسان'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='note_type_heate_speech',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='هل هو خطاب تميّزي على أساس العرق أو الدين أو أو النوع الجندري أو الطائفة أو القوميّة؟'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='result_of_verfication',
            field=models.CharField(blank=True, choices=[('0', 'مقبولة'), ('1', 'مرفوضة'), ('2', 'بحث عن مانحين')], max_length=255, null=True, verbose_name='نتيجة التحقق'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='rspect_coppyright',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل يُراعي حقوق الملكية الفكرية؟'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='rspect_legal_coppyright',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='-هل يُراعي الحق في الخصوصيّة والصور؟'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='rspect_right_human',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل يُراعي شرعة حقوق الإنسان؟'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='sumary_of_study',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='ملاحظات إضافية تتضمن أية ملاحظات حول الحالة'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='traning_partcipate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='المشاركة بورشات سابقة'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='type_heate_speech',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل هو خطاب تميّزي على أساس العرق أو الدين أو أو النوع الجندري أو الطائفة أو القوميّة؟'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='urg_mark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='درجة الطوارئ'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='verfication_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آلية التحقق'),
        ),
        migrations.AlterField(
            model_name='supportorg',
            name='date_of_response',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اﻹحالة'),
        ),
        migrations.AlterField(
            model_name='supportorg',
            name='date_of_result',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اﻹحالة'),
        ),
        migrations.AlterField(
            model_name='supportorgchild',
            name='support1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Support_descrption', verbose_name='الجهة الداعمة'),
        ),
    ]
