# Generated by Django 3.0.4 on 2020-09-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_from_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='لاسم ')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='الايميل')),
                ('state_summary', models.TextField(blank=True, max_length=1500, null=True, verbose_name='شرح معلومات وفق الجهة المحولة')),
                ('scm_summary', models.TextField(blank=True, max_length=1500, null=True, verbose_name='شرح معلومات وفق الجهة المحولة')),
                ('support1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Support_descrption', verbose_name='الجهة المحولة')),
            ],
            options={
                'verbose_name_plural': 'طلبات التحقق من الجهات الخارجية',
            },
        ),
    ]
