# Generated by Django 3.0.4 on 2020-09-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='case_org',
        ),
    ]
