# Generated by Django 3.0.4 on 2020-09-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_app_from_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_from_org',
            name='date_of_response',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اﻹحالة'),
        ),
    ]
