# Generated by Django 3.0.4 on 2020-09-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_casefile_case_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('descrpiton', models.CharField(max_length=255, null=True, verbose_name='وصف الملف المرفق')),
                ('case_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.app_from_org')),
            ],
            options={
                'verbose_name_plural': 'صندوق الوثائق',
            },
        ),
    ]
