# Generated by Django 2.2.12 on 2020-08-29 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_current_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='registration_media_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_media_act', to='account.RegisterMediaAct'),
        ),
    ]
