# Generated by Django 2.2.12 on 2020-09-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200902_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='victim',
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='worker',
        ),
    ]
