# Generated by Django 3.1 on 2020-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200820_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMediaAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('1', 'أنثى'), ('2', 'ذكر'), ('3', 'أفضل أن لا أحدد')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'أنثى'), ('2', 'ذكر'), ('3', 'أفضل أن لا أحدد')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='صورة شخصية'),
        ),
    ]
