# Generated by Django 3.0.4 on 2020-09-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_casefile_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile_org',
            name='case_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_org', to='account.app_from_org'),
        ),
    ]
