# Generated by Django 3.0.4 on 2020-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200923_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_from_org',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الاسم '),
        ),
    ]
