# Generated by Django 3.0.4 on 2020-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200923_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='checking',
            name='colse_or_open',
            field=models.CharField(blank=True, choices=[('0', 'مقبولة'), ('1', 'مرفوضة')], max_length=255, null=True, verbose_name='متابعة الحالة'),
        ),
    ]
