# Generated by Django 3.1 on 2020-08-23 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20200823_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMediaAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_state', models.CharField(choices=[('single', 'أعزب / عزباء'), ('married', 'متزوج / متزوجة'), ('divorced', 'مطلق / مطلقة'), ('widow', 'أرمل / أرملة')], max_length=30, verbose_name='الوضع العائلي')),
                ('have_kids', models.CharField(blank=True, choices=[('0', 'لا'), ('1', 'نعم')], max_length=50, null=True, verbose_name='هل لديك أولاد ؟')),
                ('number_kids', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد اﻷولاد')),
                ('summary_family', models.TextField(blank=True, max_length=2000, null=True, verbose_name='ملخص وضعك العائلي')),
                ('medical_state_q', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=50, verbose_name='هل لديك وضع صحي خاص ؟')),
                ('medical_state_des', models.TextField(blank=True, max_length=3000, null=True, verbose_name='اشرح وضعك الصحي')),
                ('education_level', models.CharField(choices=[('1', 'مادون الثانوي'), ('2', 'الثانوي'), ('3', 'الجامعي'), ('4', 'دراسات عليا')], max_length=100, verbose_name='المستوى التعليمي')),
                ('job', models.CharField(choices=[('1', 'مراسل / مراسلة '), ('2', 'محرر / محررة '), ('3', 'مصور / مصورة '), ('4', 'مراسل حربي / مراسلة حربية'), ('5', 'مراسل عسكري / مراسلة عسكرية'), ('6', 'كاتب/ة- مدير/ة مكتب إعلامي '), ('7', 'رئيس تحرير / رئيسة تحرير'), ('8', ' معد تقارير / معدة تقارير'), ('9', ' سيناريست '), ('10', ' مدير / مديرة قسم إنتاج'), ('11', 'منسق إعلامي / منسقه إعلاميه'), ('12', 'مونيتير'), ('13', 'مخرج / مخرجة'), ('14', 'منتج / منتجة'), ('15', 'متحدث إعلامي /متحدثة إعلامية'), ('16', 'عامل / عاملة في المجال اﻹعلامي'), ('17', 'ناشط إعلامي / ناشطة إعلامية'), ('18', 'مقدم / مقدمة برامج'), ('19', 'مذيع / مذيعة'), ('20', 'فنان تشكيلي / فنانة تشكيلية'), ('21', 'ممثل / ممثلة'), ('22', 'غير ذلك')], max_length=150, verbose_name='المهنة')),
                ('experience', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل سبق عملت بأجر أو لديك خبرات سابقة ؟')),
                ('if_article_linke', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل لديك منشورة باسمك الصريح أو المستعار ؟')),
                ('articls_link_1', models.TextField(blank=True, max_length=200, null=True, verbose_name='يرجى وضع الروابط اﻹعلامية المنشورة')),
                ('if_stop_work', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل انت منقطع/ة  عن العمل الاعلامي ؟')),
                ('date_stop_work', models.DateField(blank=True, null=True, verbose_name='منذ متى منقطع/ة  عن العمل الاعلامي')),
                ('summary_of_your_state', models.TextField(blank=True, null=True, verbose_name='اكتب ملخص عن حالتك')),
                ('resource_prof', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل لديك مصادر تثبت عملك ؟')),
                ('recmond_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='مصدر1 للتثبت من عملك')),
                ('phon_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم هاتف للمصدر الاول ')),
                ('email_1', models.EmailField(blank=True, max_length=255, null=True, verbose_name='بريد الكتروني للمصدر الاول')),
                ('recmond_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='مصدر 2 للتثبت من عملك')),
                ('phon_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم هاتف للمصدر الثاني ')),
                ('email_2', models.EmailField(blank=True, max_length=255, null=True, verbose_name='بريد الكتروني للمصدر الثاني')),
                ('org_memeber', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=255, verbose_name='هل أنت عضو في أي تجمع إعلامي، أو من الموقعين على مواثيق شرف إعلامية أو سواه من المبادرات المشتركة')),
                ('details', models.TextField(blank=True, max_length=4000, null=True, verbose_name='يرجى ذكر التفاصيل')),
                ('violations', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=255, verbose_name='هل سبق أن تعرضت ﻷي نوع من أنواع الانتهاكات؟')),
                ('relation_with_org', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل لديك أي ارتباطات تنظيمية مع أي فصيل عسكري أو ديني أو تجمع سياسي أو ديني؟')),
                ('summary_of_relations', models.TextField(blank=True, null=True, verbose_name='الرجاء اﻹجابة مع ذكر التفاصيل')),
                ('type_of_dmande', models.CharField(choices=[('1', 'مناصرة'), ('2', 'إيجاد فرصة عمل'), ('3', 'دعم قانوني'), ('4', 'دعم طبي'), ('5', 'دعم ملف اللجوء - تأشيرات خروج'), ('6', 'دعم الانتقال اﻵمن'), ('7', 'الدعم المعيشي'), ('8', 'الدعم التقني'), ('9', 'دعم بطاقات صحفية'), ('10', 'رسائل توصية'), ('11', 'خروج آمن'), ('12', 'غير ذلك')], max_length=50, verbose_name='طبيعة المساعدة المطلوبة')),
                ('resaon_for_help', models.TextField(blank=True, null=True, verbose_name='رجاء اكتب ملخص لسبب طلب المساعدة')),
                ('list_of_tools', models.TextField(blank=True, max_length=255, null=True, verbose_name='إن كان الدعم المطلوب متعلق بمستلزمات خاصة بالعمل، نرجو تزويدنا بقائمة الأسعار')),
                ('last_job_salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='يرجى ذكر آخر عمل تقاضيت منه أجر وقيمة الأجر')),
                ('reason_stopping_job', models.TextField(max_length=1500, verbose_name='لماذا لا تستطيع أن تعمل بأجر في الوقت الحالي؟')),
                ('summary_of_help', models.TextField(max_length=2000, verbose_name='يرجى شرح الوضع الحالي')),
                ('other_org_demand', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=255, verbose_name='هل تقدمت بطلب مساعدة ﻷي منظمة سابقاً؟')),
                ('name_org', models.TextField(blank=True, max_length=1500, null=True, verbose_name='يرجى ذكر اسم المنظمة / المنظمات')),
                ('date_of_demand_org', models.DateField(blank=True, null=True, verbose_name='نرجو معرفة تاريخ تقديم الطلب ؟')),
                ('type_of_demand_other_org', models.TextField(blank=True, max_length=1500, null=True, verbose_name='ما هي طبيعة الطلب؟')),
                ('result_of_demand_other_org', models.TextField(blank=True, max_length=1500, null=True, verbose_name='ما هي نتيجة الطلب؟')),
                ('know_support_programme', models.TextField(max_length=1500, verbose_name='كيف علمت ببرنامج الدعم ؟')),
                ('training_media', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=30, verbose_name='هل سبق أن شاركت بأي ورشات أو دورات لتطوير الخبرات اﻹعلامية أو الحقوقية؟')),
                ('details_traning_media', models.TextField(blank=True, max_length=1500, null=True, verbose_name='يرجى ذكر التفاصيل')),
                ('state_step', models.CharField(blank=True, choices=[('1', 'لم يتم البدء بالمعالجة'), ('2', 'الخطوة الاولى'), ('3', 'الخطوة الثانية'), ('4', 'الخطوة الثالثة'), ('5', 'تمت المعالجة'), ('6', 'تحميل ملفات مرفقة')], default=1, max_length=30, null=True, verbose_name='المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_org_state_1', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.support_descrption', verbose_name='الجهة المحولة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, verbose_name='اسم الجهة المشغلة')),
                ('job_title', models.CharField(max_length=255, verbose_name='المسمى الوظيفي')),
                ('job_location', models.CharField(max_length=255, verbose_name='مكان العمل')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء العمل')),
                ('until_now', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل تعمل حتى اﻵن ؟')),
                ('end_date', models.DateField(null=True, verbose_name='تاريخ انتهاء العمل')),
                ('if_salary', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل كنت تعمل بأجر ؟')),
                ('salary', models.CharField(max_length=255, null=True, verbose_name='اذكر آخر راتب تقاضيته من هذا العمل')),
                ('registration_media_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_media_act', to='account.registermediaact')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('1', ' اعتقال'), ('2', 'اختطاف'), ('3', 'منع من العمل'), ('4', 'مصادرة معدات'), ('5', 'اعتداء بالضرب'), ('6', 'اصابة'), ('7', 'تهديد'), ('8', 'ابتزاز'), ('9', 'غير ذلك')], max_length=200, null=True, verbose_name='نوع الانتهاك')),
                ('date_of_violation', models.DateField(blank=True, verbose_name='تاريخ الانتهاك ')),
                ('responsibility', models.TextField(choices=[('1', 'القوات الحكومية'), ('2', 'فصائل المعارضة المسلحة'), ('3', 'الادارة الذاتية'), ('4', 'داعش'), ('5', 'غير ذلك')], max_length=500, null=True, verbose_name='من هي الجهة المسؤولة عن الانتهاك؟')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registermediaact')),
            ],
        ),
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/', verbose_name='ملف')),
                ('docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registermediaact', verbose_name='docs')),
            ],
            options={
                'verbose_name': ' ملفات',
            },
        ),
    ]
