# Generated by Django 3.0.4 on 2020-09-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_supportorgchild_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportorgchild',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ملاحظات'),
        ),
    ]
