# Generated by Django 3.1 on 2020-08-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_docs_registermediaact_violation_workdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportOrgchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة مقدرة باليورو')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registermediaact')),
                ('support1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.support_descrption', verbose_name='الجهة الداعمة ')),
            ],
        ),
        migrations.CreateModel(
            name='SupportOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_response', models.DateField(blank=True, verbose_name='تاريخ الإحالة ')),
                ('result_of_org', models.CharField(choices=[('0', 'مقبول'), ('1', 'مرفوض')], default=False, max_length=255, null=True, verbose_name='النتيجة')),
                ('date_of_result', models.DateField(blank=True, verbose_name='تاريخ الإحالة ')),
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.registermediaact')),
            ],
        ),
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_updat', models.DateField(auto_now=True, null=True, verbose_name='تاريخ اخر تحديث ')),
                ('tiitle_of_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الحالة')),
                ('urg_mark', models.CharField(blank=True, max_length=255, null=True, verbose_name='درجة الطوارئ ')),
                ('confirm_stat', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الحالة ')),
                ('verfication_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='آلية التحقق ')),
                ('total_of_note', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name=' مجموع النقاط')),
                ('family_state_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='الوضع العائلي')),
                ('medical_state', models.CharField(blank=True, max_length=30, null=True, verbose_name='-الوضع الطبي ')),
                ('medical_state_note', models.CharField(blank=True, max_length=30, null=True, verbose_name='تقيم الوضع الصحي')),
                ('educatton_level_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='التحصيل العلمي')),
                ('cruntly_adre', models.CharField(blank=True, max_length=30, null=True, verbose_name='\tتقيم خطورة مكان الإقامة الحالي  ')),
                ('traning_partcipate', models.CharField(blank=True, max_length=30, null=True, verbose_name='\tالمشاركة بورشات سابقة')),
                ('member_in_journal', models.CharField(blank=True, max_length=30, null=True, verbose_name='هل هو عضو في مجمع صحفي')),
                ('hase_violants', models.CharField(blank=True, default=1, max_length=30, null=True, verbose_name='تعرّض مُقدّم الطلب لأيّ انتهاكات ')),
                ('is_related_with_media', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل طلب الدعم مرتبط بالعمل الصحفي')),
                ('number_of_year_exprince', models.CharField(blank=True, choices=[('0', 'أقل من عامين'), ('1', 'عامين إلى خمسة'), ('2', 'أكثر من خمسة ')], max_length=255, null=True, verbose_name='عدد سنوات الخبرة في العمل')),
                ('note_of_year_experince', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='تقيم عدد سنوات الخبرة في العمل')),
                ('note_paid_job', models.CharField(blank=True, max_length=255, null=True, verbose_name='تقيم العمل بإجر')),
                ('manitry_realtion', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل لديه ارتباطات عسكرية')),
                ('note_manitry_realtion', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة حول لارتباطات العسكرية')),
                ('is_thier_info_correct', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل قدم معلومات صحيحة ضمن طلب الدعم ')),
                ('is_thier_heate_speech', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='-\tهل يُحرّض على العنف والكراهية؟ أو الإرهاب أو الطائفيّة؟ ')),
                ('is_thier_heate_speech_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح لتقيم التحريض ')),
                ('type_heate_speech', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل هو خطاب تميّزي على أساس العرق أو الدين أو أو النوع الجندري أو الطائفة أو القوميّة؟ ')),
                ('note_type_heate_speech', models.CharField(blank=True, max_length=255, null=True, verbose_name='هل هو خطاب تميّزي على أساس العرق أو الدين أو أو النوع الجندري أو الطائفة أو القوميّة؟ ')),
                ('rspect_legal_coppyright', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='-هل يُراعي الحق في الخصوصيّة والصور؟  ')),
                ('note_rspect_legal_coppyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح لمراعاة خصوصية الصور ')),
                ('mark_rspect_legal_coppyright', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='-تقيم الحق في الخصوصيّة والصور؟')),
                ('rspect_coppyright', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل يُراعي حقوق الملكية الفكرية؟ ')),
                ('note_rspect_coppyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح لاحترام حقوق النشر ')),
                ('mark_rspect_coppyright', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name=' تقيم شرح لاحترام حقوق النشر  ')),
                ('rspect_right_human', models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل يُراعي شرعة حقوق الإنسان؟  ')),
                ('note_rspect_right_human', models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح لتقيم احترام حقوق الانسان ')),
                ('mark_rspect_right_human', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='تقيم احترام حقوق الانسان ')),
                ('prof_media', models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], max_length=255, null=True, verbose_name='المهنية في صياغة الاخبار')),
                ('first_recmond_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المعرف الاول')),
                ('here_speech_1', models.CharField(blank=True, choices=[('0', 'التنيجة ايجابية'), ('1', 'النتيجة سلبية')], max_length=255, null=True, verbose_name='شهادة المعرف')),
                ('recmond_1att', models.CharField(blank=True, max_length=255, null=True, verbose_name='اثبات شهادة المعرف الأول')),
                ('second_recmond_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المعرف الثاني')),
                ('here_speech_2', models.CharField(blank=True, choices=[('0', 'التنيجة ايجابية'), ('1', 'النتيجة سلبية')], max_length=255, null=True, verbose_name='شهادة المعرف')),
                ('recmond_2_att', models.CharField(blank=True, max_length=255, null=True, verbose_name='اثبات شهادة المعرف الثاني')),
                ('check_responsabl_group_opnion', models.TextField(blank=True, max_length=255, null=True, verbose_name='تحقق مسؤول التواصل أو المتعاونين تسجيل المعلومات الواردة حول طالب الدعم ')),
                ('date_of_verficaton', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء من التحقق ')),
                ('result_of_verfication', models.CharField(blank=True, choices=[('0', 'مقبولة'), ('1', 'مرفوضة'), ('2', 'بحث عن مانحين')], max_length=255, null=True, verbose_name='نتيجة التحقق ')),
                ('sumary_of_study', models.TextField(blank=True, max_length=255, null=True, verbose_name='ملاحظات إضافية تتضمن أية ملاحظات حول الحالة ')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.registermediaact')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('descrpiton', models.CharField(max_length=255, null=True, verbose_name='وصف الملف المرفق ')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registermediaact')),
            ],
        ),
    ]
