# Generated by Django 3.0.4 on 2020-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_checking_colse_or_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='colse_or_open',
            field=models.CharField(blank=True, choices=[('0', 'مفتوح '), ('1', 'مغلق')], max_length=255, null=True, verbose_name='متابعة الحالة'),
        ),
    ]
