# Generated by Django 3.1 on 2020-08-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_casefile_checking_supportorg_supportorgchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermediaact',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
