# Generated by Django 2.1.15 on 2020-11-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200923_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_region',
            field=models.CharField(blank=True, choices=[('0', ' الحسكة'), ('1', ' حلب'), ('2', 'الرقة'), ('3', 'السويداء '), ('4', 'ريف دمشق '), ('5', 'درعا '), ('6', 'دير الزور'), ('7', 'حماه'), ('8', ' حمص '), ('9', ' إدلب '), ('10', ' اللاذقية '), ('11', 'القنيطرة'), ('12', 'دمشق'), ('13', 'طرطوس')], max_length=100, null=True, verbose_name='في أي محافظة ؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('0', ' الحسكة'), ('1', ' حلب'), ('2', 'الرقة'), ('3', 'السويداء '), ('4', 'ريف دمشق '), ('5', 'درعا '), ('6', 'دير الزور'), ('7', 'حماه'), ('8', ' حمص '), ('9', ' إدلب '), ('10', ' اللاذقية '), ('11', 'القنيطرة'), ('12', 'دمشق'), ('13', 'طرطوس')], max_length=100, null=True, verbose_name='من أي محافظة ؟'),
        ),
    ]
