# Generated by Django 3.0.4 on 2020-09-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200903_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportorgchild',
            options={'verbose_name_plural': 'الاستجابة والجهات الداعمة'},
        ),
        migrations.AlterField(
            model_name='checking',
            name='hase_violants',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تعرّض مُقدّم الطلب لأيّ انتهاكات'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='result_of_verfication',
            field=models.CharField(blank=True, choices=[('0', 'مقبولة'), ('1', 'مرفوضة'), ('2', 'بحث عن مانحين'), ('3', 'عدم استجابة طالب الدعم لأسئلة التحقق الإضافية ')], max_length=255, null=True, verbose_name='نتيجة التحقق'),
        ),
    ]
