# Generated by Django 3.1 on 2020-08-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200823_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportorg',
            name='date_of_result',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإحالة '),
        ),
        migrations.AlterField(
            model_name='supportorg',
            name='result_of_org',
            field=models.CharField(blank=True, choices=[('0', 'مقبول'), ('1', 'مرفوض')], default=False, max_length=255, null=True, verbose_name='النتيجة'),
        ),
    ]
