# Generated by Django 3.1 on 2020-08-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200824_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermediaact',
            name='if_article_linke',
            field=models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل لديك منشورات باسمك الصريح أو المستعار ؟'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='date_of_violation',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاك '),
        ),
        migrations.AlterField(
            model_name='violation',
            name='responsibility',
            field=models.TextField(blank=True, choices=[('1', 'القوات الحكومية'), ('2', 'فصائل المعارضة المسلحة'), ('3', 'الادارة الذاتية'), ('4', 'داعش'), ('5', 'غير ذلك')], max_length=500, null=True, verbose_name='من هي الجهة المسؤولة عن الانتهاك؟'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(blank=True, choices=[('1', ' اعتقال'), ('2', 'اختطاف'), ('3', 'منع من العمل'), ('4', 'مصادرة معدات'), ('5', 'اعتداء بالضرب'), ('6', 'اصابة'), ('7', 'تهديد'), ('8', 'ابتزاز'), ('9', 'غير ذلك')], max_length=200, null=True, verbose_name='نوع الانتهاك'),
        ),
    ]
