# Generated by Django 3.0.4 on 2020-08-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200824_1723'),
        ('account', '0015_auto_20200824_2354'),
    ]

    operations = [
    ]
